"""Central configuration for the pricing bot.

Override any of these with environment variables so the project works both
in this repo (data/quotation_items.xlsx) and on a local Windows machine
(e.g. C:\\Harshal\\Quotation Dataset\\...\\quotation_items.xlsx).
"""

import os
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent

# Path to the historical quotation Excel file.
DATA_PATH = os.environ.get(
    "QUOTATION_DATA_PATH",
    str(PROJECT_ROOT / "data" / "quotation_items.xlsx"),
)

# Version-controlled estimator corrections are kept separate from the raw
# workbook.  Only records explicitly marked approved are applied.
CORRECTIONS_PATH = os.environ.get(
    "PRICING_CORRECTIONS_PATH",
    str(PROJECT_ROOT / "data" / "pricing_corrections.json"),
)

# Generated by scripts/evaluate_families.py and served read-only by the API.
FAMILY_READINESS_PATH = os.environ.get(
    "FAMILY_READINESS_PATH",
    str(PROJECT_ROOT / "data" / "family_readiness.json"),
)

# Offline-only V3 context-model scorecard. The API reads this JSON snapshot;
# it never loads a fitted model or applies an adjustment from this file.
CONTEXT_MODEL_READINESS_PATH = os.environ.get(
    "CONTEXT_MODEL_READINESS_PATH",
    str(PROJECT_ROOT / "data" / "context_model_readiness.json"),
)

# DeepSeek API settings. The key MUST come from the environment.
DEEPSEEK_API_KEY = os.environ.get("DEEPSEEK_API_KEY", "")
DEEPSEEK_BASE_URL = os.environ.get("DEEPSEEK_BASE_URL", "https://api.deepseek.com")
DEEPSEEK_MODEL = os.environ.get("DEEPSEEK_MODEL", "deepseek-chat")
DEEPSEEK_TIMEOUT = int(os.environ.get("DEEPSEEK_TIMEOUT", "60"))

# Default currency used when the dataset does not state one per row.
# The attached dataset's Quotation Summary sheet is 100% AED.
DEFAULT_CURRENCY = os.environ.get("DEFAULT_CURRENCY", "AED")

# Similarity search weights: final = TEXT_WEIGHT*text + ATTR_WEIGHT*attributes
TEXT_WEIGHT = 0.55
ATTR_WEIGHT = 0.45

# Matches below this final score are considered weak.
WEAK_MATCH_THRESHOLD = 0.35

# When both the input and a dataset item have a recognized item type
# (planter, litter bin, bench, ...) and they differ, the item's final score
# is multiplied by this penalty so same-type items always outrank it.
TYPE_MISMATCH_PENALTY = 0.45

# A recognized subtype mismatch (for example a removable versus fixed
# bollard, or a planter with seating versus a standalone planter) is a strong
# signal that two records are not direct pricing comparables.
SUBTYPE_MISMATCH_PENALTY = 0.55

# When two per-item products of the SAME type state sizes whose largest
# dimensions differ by more than this ratio, the item is a different size
# class (a 50mm frame member is not a comparable for a 2.6m planter) and
# its score is penalized. Never applied to per-metre/per-m2 items, whose
# stated sizes are profiles, not product scale.
SIZE_MISMATCH_RATIO = 4.0
SIZE_MISMATCH_PENALTY = 0.6

# An item that includes integrated seating when the input does not (or
# vice versa) is priced for a different product; its score is penalized.
SEATING_MISMATCH_PENALTY = 0.7

# Company rule: supply and installation is 20% more expensive than supply
# only / supply and delivery. Historical rates are converted to the input's
# scope basis before the anchor and clamp are computed.
SCOPE_INSTALL_UPLIFT = float(os.environ.get("SCOPE_INSTALL_UPLIFT", "1.20"))

# Pricing is always computed from a fixed set of the strongest matches,
# independent of how many matches the user displays (top_k). A match joins
# the pricing set when its score is within PRICING_RELATIVE_CUTOFF of the
# best score; the set has between MIN and MAX members.
PRICING_MIN_MATCHES = 3
PRICING_MAX_MATCHES = 5
PRICING_RELATIVE_CUTOFF = 0.85

# Production comparable gates.  Pricing always considers a fixed number of
# ranked candidates, independent of how many rows the UI displays.
PRICING_CANDIDATE_RESULTS = 50
PRODUCTION_MIN_COMPARABLES = 3
PRODUCTION_MIN_BEST_SCORE = 0.45
PRODUCTION_MAX_RATE_RATIO = 2.0
PRODUCTION_GATE_WITHIN_20 = 0.80
PRODUCTION_GATE_MIN_CASES = 25

# V2 family-release gates.  A shadow family can be marked ready for estimator
# review only after passing every threshold; deployment still requires an
# explicit allow-list change in production_pricing.py.
V2_GATE_MIN_COVERAGE = 0.35
V2_GATE_MAX_MEDIAN_APE = 0.15
V2_GATE_MAX_P90_APE = 0.40
V2_GATE_MAX_FACTOR2_ERRORS = 0
V2_GATE_MIN_QUOTE_GROUPS = 5

# V3 contextual-adjustment evidence gates.  Passing these thresholds means a
# quantity/supplier/date/location field is safe to model, not that it may be
# used in production.  Activation additionally requires lineage-held-out
# calibration and an explicit allow-list change.
V3_CONTEXT_MIN_COVERAGE = 0.35
V3_CONTEXT_MIN_QUOTE_GROUPS = 12
V3_CONTEXT_MIN_DISTINCT_VALUES = 3
V3_CONTEXT_MIN_GROUPS_PER_LEVEL = 4
V3_CONTEXT_MIN_MATCHED_COHORTS = 3
V3_DATE_MIN_SPAN_DAYS = 180
V3_DATE_MIN_COHORT_SPAN_DAYS = 90

# V3 context-model shadow gates. These apply after the data-readiness gates.
# A candidate must beat an exact-product cohort-median baseline under complete
# quotation-lineage holdout and strictly earlier-data-only rolling folds.
V3_MODEL_MIN_CASES = 25
V3_MODEL_MIN_EVAL_QUOTE_GROUPS = 8
V3_MODEL_MIN_TRAIN_QUOTE_GROUPS = 8
V3_MODEL_MIN_TRAIN_GROUPS_PER_COHORT = 3
V3_MODEL_MIN_COHORTS = 3
V3_MODEL_MIN_TRAIN_HISTORY_DAYS = 180
V3_MODEL_MIN_COVERAGE = 0.35
V3_MODEL_MIN_WITHIN_20 = 0.80
V3_MODEL_MAX_MEDIAN_APE = 0.15
V3_MODEL_MAX_P90_APE = 0.40
V3_MODEL_MAX_FACTOR2_ERRORS = 0
V3_MODEL_MIN_MEDIAN_APE_IMPROVEMENT = 0.02
V3_MODEL_MIN_IMPROVED_CASE_SHARE = 0.55
V3_MODEL_FACTOR_MIN = 0.67
V3_MODEL_FACTOR_MAX = 1.50
V3_MODEL_MAX_CLAMP_SHARE = 0.10
V3_MODEL_MAX_FORECAST_HORIZON_DAYS = 180
V3_MODEL_RIDGE_ALPHA = 1.0

# The predicted price is clamped to this factor of the pricing set's
# historical rate range. Wide enough to allow justified spec adjustments
# (e.g. SS316 vs mild steel comps can legitimately be ~3x), while still
# catching order-of-magnitude drift.
PRICE_CLAMP_LOW = 0.4    # x lowest rate in pricing set
PRICE_CLAMP_HIGH = 3.0   # x highest rate in pricing set
